### ISSUE TITLE
Thumbnails errors

### ISSUE THREAD

**Issue by WirthmU** [thomasjacquin/allsky-website#120]
I have installed the latest allsky-website files. The website is running on a NAS.

http://80.219.133.218/Saanenmoeser/allskyS1.htm

Things are running smoothly but not the thumbnails directories (startrails, keograms, timelapses).

I got errors displaying the directories pages:

![image](https://user-images.githubusercontent.com/27740335/177281928-d481e8e5-8251-4321-a12d-8fc95e36d6ae.png)

**Comment by StereotypicalSquirrel** [comment]
This are two typos on lines 259 and 260 in functions.php

Change $thum_dir to $thumb_dir

**Comment by WirthmU** [comment]
It worked perfectly after correcting it. Thank you @StereotypicalSquirrel !
