### ISSUE TITLE
Website error  messages.

### ISSUE THREAD

**Issue by maserowik** [thomasjacquin/allsky-website#131]
it has been a while since I had my allsky working.  I finally got my allsky backup and running.  I did the latest put of the software but iI am now getting this error message on my hosting site.

Hosting site = Hostinger
Site name n3bsq.com
when I click on the
timelapse/keogram and  the startrials getting error message 

![image](https://user-images.githubusercontent.com/25713782/205686283-dbf5159b-6971-4ae9-93c2-9e5d78e6a6f3.png)

![image](https://user-images.githubusercontent.com/25713782/205686359-09dd97d4-33a1-4a42-9339-fe4f323aed0b.png)

![image](https://user-images.githubusercontent.com/25713782/205686604-2e7e4fa0-d9a6-4ada-8ca5-a8826bfd1000.png)

**Comment by EricClaeys** [comment]
@maserowik Sorry for the late reply.  The software on the remote host (or whatever machine created those error messages) appears out of date.  The error about "undefined variable thum_dir" was fixed so I suggest grabbing the newest code and copying to your server.
Also, make sure the `videos`, `startrails`, and `keograms` directories have a subdirectory called `thumbnails`.

Let me know how it goes.

**Comment by EricClaeys** [comment]
@maserowik   I just noticed that I fixed the incorrectly spelled "thum_dir" in a couple places but missed it on line 260 in the current code.  It should be `thumb_dir`.

**Comment by EricClaeys** [comment]
The new release v2023.05.01 of Allsky and the Allsky Website were released today and I beliece the error is fixed.
