### ISSUE TITLE
Constellation overlay issues on mobile

### ISSUE THREAD

**Issue by Mr-Groch** [thomasjacquin/allsky-website#139]
Hi, contellation overlay has 2 bugs on mobile:
1. It can be rotated by touch and drag ("mouse": false, "keyboard": false in config - on dekstop it can't be rotated)
2. It is not properly diisplayed on mobile, on desktop:
![image](https://github.com/thomasjacquin/allsky-website/assets/20594810/f7e9d075-ef59-42fb-bbcf-007c297bc368)
On mobile:
![image](https://github.com/thomasjacquin/allsky-website/assets/20594810/9cf3d1ed-e92d-46ee-9e9c-ac29a5c2c377)

**Comment by EricClaeys** [comment]
Interesting.  I never tried rotating on a mobile when "mouse" was false.
Neither of these issues will likely be fixed anytime soon, unless we can find someone with very good javascript experience.
I have spent countless hours trying to get the overlay to resize properly on smaller devices but have never gotten it to work.  It's better but still needs a javascript expert.

By any chance are you an expert in javascript?

**Comment by Mr-Groch** [comment]
No, I'm not good in js... I'm preferring backend stuff :)

I've just found how to disable rotation of constellation by touch and drag. In virtualsky/virtualsky.js, line 1616 in `}).on('touchmove',{sky:this},function(e){`: `if(s.dragging && s.mouse){` (was `if(s.dragging){`)

No idea about constellation overlay algning on mobile...

**Comment by EricClaeys** [comment]
@Mr-Groch    Thanks much.  I added this fix to the next major release.

**Comment by Mr-Groch** [comment]
Hi, I've found another workaround for misaligned constellation overlay on mobile

Changing in index.php:

```html
<meta name="viewport" content="width=device-width, initial-scale=1">
```

To:

```html
<meta name="viewport" content="width=1024">
```

Will make to render on mobile devices properly - small but without issues - it can be easily zoomed with pan & zoom

**Comment by EricClaeys** [comment]
How well does this work with tablets and PCs?

**Comment by Mr-Groch** [comment]
I've tested on my Xiaomi Redmi Note 11 and PC with FHD screen - on PC no noticeable change (screen width is bigger that declared viewport), on mobile it is better as mentioned earlier

Also tested on Chrome de tools:

Samsung Galaxy S8+:
![image](https://github.com/thomasjacquin/allsky-website/assets/20594810/4dac4e9f-6584-41e3-be0a-15deec67f24f)

IPad Air:
![image](https://github.com/thomasjacquin/allsky-website/assets/20594810/c2d948da-b70f-44a6-a87a-aefb63c7db9a)

Nest Hub:
![image](https://github.com/thomasjacquin/allsky-website/assets/20594810/a05ba074-8ea2-4892-a664-dc8a0bc55b7b)

Surface 7 Pro:
![image](https://github.com/thomasjacquin/allsky-website/assets/20594810/a9793237-2e1c-43d3-bf88-d1715f63f107)

**Comment by Alex-developer** [comment]
@EricClaeys I'll add it to my list :-)

Could do with a little break from the new UI so will take a look at the weekend
