### ISSUE TITLE
Instructions on how setup allsky-website [waiting for response]

### ISSUE THREAD

**Issue by wannaberocker** [thomasjacquin/allsky-website#14]
Hello, I would like to get this all allsky-website up and running. All seems to work but the timelapse, keograms, or the star trail image archives..the link gives me a 404 error. What am I doing wrong? Thanks

**Comment by wannaberocker** [comment]
I seem to have it working now but the image isn't being uploaded how can I do this?

**Comment by wannaberocker** [comment]
On other words, what do do for imageName: ...??

**Comment by wannaberocker** [comment]
Another weird quirk....Internet Explorer browser instantly reflects my changes to config.js and controller.js files while Chrome does not. Why is that? I'm just trying to set the overlay up correctly and I am totally lost on how to do this. Any help would be appreciated Thanks.

**Comment by wannaberocker** [comment]
This is so incredibly difficult to what should be an almost mindless adjustment, I'd like to offer money but at this point its been so frustrating I feel like I should be getting paid LOL! Anyway I've gotta take a step back as I have been screwing with this for 5 days straight now.

**Comment by thomasjacquin** [comment]
Hello, can you share the url? I will take a look. It can be caused by various reasons. Sometimes the hosting account doesn't have PHP installed, sometimes it's a permission issue on the directories.

**Comment by wannaberocker** [comment]
Here is the URL, also how do you adjust the sky overlay to fit properly? I seem to be chasing my tail on that. Thanks.

http://wannaberocker.ddns.net:10700/allsky-website/

**Comment by thomasjacquin** [comment]
It looks like I can't access the URL but from what I can see, you've installed the website on the RPi. I think it should work as well but originally this project was designed to be installed onto a hosting account.
That should still function properly though. I have accessed the public page here (http://wannaberocker.ddns.net:10700/public.php) For the constellation overlay, it covers a 180 degrees field of view so that might not fit your current field of view. It looks like your lens doesn't cover the whole sky. You may need a different type of projection. See the projection examples on the VirtualSky project page (http://slowe.github.io/VirtualSky/).

**Comment by wannaberocker** [comment]
I am unsure why you cannot access the URL as I have had a few other people able to access it. Is there a way to get the timelapse, keograms, and star trails to appear with the server installed on the RPi? I’m just looking to do that for now if possible. Thanks. 


Sent from Yahoo Mail for iPhone


On Monday, October 14, 2019, 11:58 PM, Thomas Jacquin <notifications@github.com> wrote:


It looks like I can't access the URL but from what I can see, you've installed the website on the RPi. I think it should work as well but originally this project was designed to be installed onto a hosting account.
That should still function properly though. I have accessed the public page here (http://wannaberocker.ddns.net:10700/public.php) For the constellation overlay, it covers a 180 degrees field of view so that might not fit your current field of view. It looks like your lens doesn't cover the whole sky. You may need a different type of projection. See the projection examples on the VirtualSky project page (http://slowe.github.io/VirtualSky/).

**Comment by maserowik** [comment]
> I have since figured out how to fix my broken links on the allsky-website page. It was simply going to the index.html file and editing the href for each item. That was easy. One problem though remains...the startrails and keograms, although routed correctly now does not display any of the jpgs saved in the directory the link points to. Why is this? FYI the url is now http://rko.ddns.net:10700/allsky-website/

It appears that you are using you raspberry pi to locally host the allsky-website.  Would you be kind enough to share how you got it running?  

Thanks
Mike

**Comment by Torakin9366** [comment]
Hallo zusammen. Ich möchte auch gerne die Webseite einrichten. Habe die zip Datei auf meinem Raspberry pi 4 herunter geladen und entpackt, der Ordner liegt noch im Download Ordner. Meine Daten hab ich in der config.js schon geändert. Was muss ich jetzt weiteres tun, bin absoluter Neuling auf dem Gebiet. Meine Allsky Kamera läuft und die Daten werden auf meinem Ftp Server gespeichert.
Danke schon mal für die Bemühung
Torsten

**Comment by klingonio** [comment]
Hallo

> 
> 
> Hallo zusammen. Ich möchte auch gerne die Webseite einrichten. Habe die zip Datei auf meinem Raspberry pi 4 herunter geladen und entpackt, der Ordner liegt noch im Download Ordner. Meine Daten hab ich in der config.js schon geändert. Was muss ich jetzt weiteres tun, bin absoluter Neuling auf dem Gebiet. Meine Allsky Kamera läuft und die Daten werden auf meinem Ftp Server gespeichert.
> Danke schon mal für die Bemühung
> Torsten

Hi Torsten,
an dem Punkt bin ich auch. Schau mal in dem Thread https://github.com/thomasjacquin/allsky-website/issues/7
Das sollte Dein Problem lösen. Ich versuche mich da auch mal .... melde mich.

**Comment by wannaberocker** [comment]
> > I have since figured out how to fix my broken links on the allsky-website page. It was simply going to the index.html file and editing the href for each item. That was easy. One problem though remains...the startrails and keograms, although routed correctly now does not display any of the jpgs saved in the directory the link points to. Why is this? FYI the url is now http://rko.ddns.net:10700/allsky-website/
> 
> It appears that you are using you raspberry pi to locally host the allsky-website. Would you be kind enough to share how you got it running?
> 
> Thanks
> Mike

Hi Mike, sorry I did not see this until today. I can remember mostly what I did, I installed the allsky-website onto the var/www/html directory on a raspberry pi 4. I had to edit some code to get the timelapse, startrails, and keograms to be archived and viewed properly. I even use dropbox-uploader via the endOfNight script to upload the high quality stills to use to make a higher quality timelapse if I wanted to do so.

**Comment by klingonio** [comment]
Hi wannaberocker
what code did you edit?
i also installed the allsky-website on my pi under /var/www/html and had the same problems (HTML Error 404 ...)

**Comment by wannaberocker** [comment]
Try to get everything to work locally first. I can’t exactly remember what all I did. I saved all my edited files. I’ll see if I can get them to you. 


Sent from Yahoo Mail for iPhone


On Wednesday, August 19, 2020, 2:17 PM, klingonio <notifications@github.com> wrote:




Hi wannaberocker
what code did you edit?
i also installed the allsky-website on my pi under /var/www/html and had the same problems (HTML Error 404 ...)

**Comment by huisinr** [comment]
Howdy !
With regards to the allsky-website portal  and  archived videos, is it possible to list the newest to the oldest in descending order?
http://www.huisinga.org/allsky/videos/
 Thanks in advanced for any suggestions!

**Comment by thomasjacquin** [comment]
See this https://github.com/thomasjacquin/allsky-website/issues/25#issuecomment-700912841

**Comment by PhotonPup** [comment]
I am struggling with this. If anyone could assist, start to finish getting the AllSky-Website onto a Pi4 and functioning that would be amazing.

**Comment by Shand359** [comment]
i have the same issue as PhotonPup.... I have no issues now getting the gui installed and running ok but no matter what i do i cannot get the website to work.....

**Comment by PhotonPup** [comment]
> i have the same issue as PhotonPup.... I have no issues now getting the gui installed and running ok but no matter what i do i cannot get the website to work.....

Hey Shand359 - I was able to get up and running thanks to the help of someone from the AllSky FB page. Because of that I put together a guide i guess you  could say in case anyone else had same issues i did. You can check what I put in place as a walk through...maybe it will help. 
https://www.photonpup.com/programming-allsky-software-onto-pi4

**Comment by EricClaeys** [comment]
@wannaberocker, can this issue be closed?  I believe an answer and a like were provided.
