### ISSUE TITLE
Installation allsky-website

### ISSUE THREAD

**Issue by Stewaro** [thomasjacquin/allsky-website#2]
how do I instal allsky-website  on my Hoster? 
Or does she run only on the Raspberry?
Greetings.

**Comment by thomasjacquin** [comment]
Hi,

You should be able to download the files and upload them to your hosting account. Nothing special about it. All you need is to change some settings (lat, long, image file name, etc). In order for the videos, startrails and keograms to be listed, you need your host to have PHP installed.

Thomas

**Comment by Stewaro** [comment]
Hello Thomas,

Thank you very much.
Unfortunately I do not reach the goal.
  "All you need is to change some settings (lat, long, image file name, etc)."
PHP is running on my host. but error viewing videos, startrails and keograms. Internal Server Error
  - The server encountered an internal error or misconfiguration and was unable to complete your request. -
look at www.allskycam-rotheul.de
can you help?
Henry.

**Comment by thomasjacquin** [comment]
Hi Henry,
It depends of the structure of your directories on your host.
I think you just need to remove `allsky` from the URL for each of those links.
Edit index.html lines 56, 57 and 58.

**Comment by Stewaro** [comment]
Hi Thomas, 
it works now.
Thank you very much.

**Comment by Kilis71** [comment]
Hi, I have a problem on allskycam web, the photos are not loaded, the settings on raspberry are giiste but on the web remains the screen loading http://www.astrokilis.altervista.org/allskycam/

**Comment by thomasjacquin** [comment]
Your host needs to have PHP running. Not all the hosts have it. Some of them only support html files.
Make sure you can use PHP files on altervista first.

**Comment by Kilis71** [comment]
how do I know?

**Comment by thomasjacquin** [comment]
It looks like their hosting plan has PHP capabilities. I'm not sure which one you are using.

**Comment by Kilis71** [comment]
Which version should I use of php

**Comment by Kilis71** [comment]
I can use versions 5.3, 5.3extra, 5.6, 5.7

**Comment by thomasjacquin** [comment]
Any version should work but use 7 if you want, it's the latest one.

**Comment by Kilis71** [comment]
the program on the server is working, what is not working and the image loading from raspberry to the server

**Comment by thomasjacquin** [comment]
You need to fill your settings in `scripts/ftp-settings.sh`
You'll need your `host`, `username`, `password` and `directories`
You will need to create these directories on the host first.

**Comment by Kilis71** [comment]
what you tell me I did but the photos do not load them. Does the domain need top-level or is it good even for the second level?

**Comment by thomasjacquin** [comment]
What do you have in IMGDIR?
It should be the path to this directory on your server. I don't know how your server is set up. It could be `/var/www/html/public_html/allsky` or something like `lamp/vhosts/www.myserver/public_html/allsky`. It's different for every host.

**Comment by Kilis71** [comment]
# FTP/SFTP settings
PROTOCOL='ftp'
USER='astrokilis'
PASSWORD='Stese16212'
HOST='astrokilis.altervista.org/'
IMGDIR='/allsky/'
MP4DIR='/allsky/videos/'
KEOGRAM_DIR='/allsky/keograms/'
STARTRAILS_DIR='/allsky/startrails/'

**Comment by Kilis71** [comment]
http://www.astrokilis.altervista.org/allsky/

**Comment by thomasjacquin** [comment]
Try these in Filezilla to make sure it's correct and it can connect and look at the directory structure on the host. Once you have all that, it should work fine.

**Comment by Kilis71** [comment]
With filezilla working, I've uploaded allsky web folders and files. But from raspberry to the altervista host they do not load

**Comment by thomasjacquin** [comment]
Try running the program manually in a terminal to see the error message:

service allsky stop
./allsky.sh

**Comment by Kilis71** [comment]
Altervista uses self-signed certificates that cause me an error during loading, can I ignore the certified?

**Comment by Kilis71** [comment]
It gives me a fatal certificate error

**Comment by thomasjacquin** [comment]
Try adding this option to any lftp calls: `ssl:verify-certificate false`

It should look like that for example in saveImageDay.sh

`lftp "$PROTOCOL"://"$USER":"$PASSWORD"@"$HOST":"$IMGDIR" -e "set net:max-retries 1; set net:timeout 20; set ssl:verify-certificate false; put $FILENAME-resize.$EXTENSION; bye" &`

saveImageNight.sh and timelapse.sh have similar calls.

**Comment by Kilis71** [comment]
I did as your instructions, now give me this error.

cd: Errore fatale: Certificate verification: certificate common name doesn't match requested host name ‘ftp.astrokilis.altervista.org’ (23:04:CA:15:B3:3B:D4:B1:A8:48:77:57:6E:22:58:9A:8C:81:33:D9)
put: image-resize.jpg: Errore fatale: max-retries exceeded (EPSV failed, will try PASV)

**Comment by Kilis71** [comment]
if I remove ftp. from the host address from the allsky console, the connection remains in progress but does not connect. I'm going crazy

**Comment by thomasjacquin** [comment]
Send me your credentials at jacquin.thomas@gmail.com and I'll give it a try on my side.

**Comment by Kilis71** [comment]
do you want host server credentials?

**Comment by thomasjacquin** [comment]
The ones you're using to connect with Filezilla.

**Comment by Kilis71** [comment]
Email sent...

**Comment by maphilli14** [comment]
This is quite intriguing and I'd like to set this up too.  Do you have a list of requirements, I see:

1) External website
2) PHP support
3) FTP file push?

what else?

**Comment by thomasjacquin** [comment]
If you want to have your live image, keograms, startrails and timelapses available on the internet, you will need a web host that supports PHP. Most of them have PHP installed.
FTP is almost always available with your hosting account because that's how you set up a website.
That's all you need.
