### ISSUE TITLE
Allsky 

### ISSUE THREAD

**Issue by maserowik** [thomasjacquin/allsky-website#21]
I am having a issue with the sidebars on the website.  I am sure I missed a configurations somewhere.  I am running allsky on a Raspberry Pi 3b.  I cannot get the video, keograms and startails to work.  

Thanks Mike

**Comment by perulero** [comment]
Me too.. ?

**Comment by maserowik** [comment]
followed 
https://github.com/thomasjacquin/allsky/issues/74
