### ISSUE TITLE
Latest videos, startrails and keograms first

### ISSUE THREAD

**Issue by DarKOrange75** [thomasjacquin/allsky-website#25]
Hi @thomasjacquin,

I see on your AllSky web site that the latest video, startrails and keograms are displayed first. How do you achieve that? On my web site the oldest is displayed first and the latest is last. Which is fine for now because my setup is new but in a few months it may be uncomfortable.

Thank you!

Laurent

**Comment by thomasjacquin** [comment]
Change this line https://github.com/thomasjacquin/allsky-website/blob/master/videos/index.php#L25 and do it for keogram and startrails as well.

**Comment by DarKOrange75** [comment]
Thank you @thomasjacquin :-)

**Comment by Kilis71** [comment]
> Change this line https://github.com/thomasjacquin/allsky-website/blob/master/videos/index.php#L25 and do it for keogram and startrails as well.
> 
> Replace with `rsort($files);`

I tried but this modification doesn't work for me
