### ISSUE TITLE
I can't see the constellations

### ISSUE THREAD

**Issue by abrosio** [thomasjacquin/allsky-website#29]
Hi Thomas and hi everyone,
I can't see the constellations but only the lines, why?
I tried all the settings but also nothing in the virtualsky.json file...
Many Thanks
Antonino

**Comment by thomasjacquin** [comment]
Are you saying `virtualsky.json` is empty on your website?
It should contain these lines: https://github.com/thomasjacquin/allsky-website/blob/master/virtualsky.json

**Comment by abrosio** [comment]
Yes the files is ok but only the grid lines are seems.
This is my site: http://abobservatory.altervista.org/allsky/

Can you add my all sky camera to the map? Thanks

**Comment by thomasjacquin** [comment]
Hi Antonio,

Did you figure out the issue? It seems to work when I look at your website. The overlay doesn't really line up with your image because of cropping I assume but the constellations are here. I'll add you to the map!

![image](https://user-images.githubusercontent.com/3053094/100651499-c13ec680-3302-11eb-8505-ca1535a1a0f4.png)

**Comment by abrosio** [comment]
It is really weird because my PCs, smartphones and macs only see the orange lines and not the constellations
![Uploading 7DA3FAAD-7E16-4FCD-B414-ED6B5619750A.jpeg…]()

**Comment by thomasjacquin** [comment]
I could be a language issue. I suppose your OS and browser is set to Italian. Try to switch temporarily to English. If it works, then I'll have to look into bringing multi language support.

**Comment by abrosio** [comment]
Great Idea Thomas, you are absolutely right, i changed the language and now it works!
how to solve?  I have seen from your map other cams in Italy which also works with Italian browsers.

**Comment by abrosio** [comment]
I found the problem!  you have to add it.json file in virtualsky / lang and then it works
Thanks

**Comment by abrosio** [comment]
Then you have to definitely act on one of the files, could you help me figure out which one?
Thanks

**Comment by abrosio** [comment]
Hello Thomas,
Did you then find the solution to be able to view the constellations in other languages too? I was not able to solve by myself unfortunately

Thanks

**Comment by thomasjacquin** [comment]
You'd probably need to add the language here as well https://github.com/thomasjacquin/allsky-website/blob/master/virtualsky/virtualsky.js#L788

**Comment by HamOP** [comment]
You can simply pull the latest version. I suggested adding `"lang": "en"` to the virtualsky.json and Thomas merged it into the official version. This will make it work independently of the site user's language setting - the only drawback is that the virtual sky names are always English which is not such a big deal in my opinion. Issue is that language is chosen according to the viewer's system language and as long as you don't have any possible language inside there, there will always be page visitors where it will not work.
