### ISSUE TITLE
image/video display order

### ISSUE THREAD

**Issue by jcauthen78** [thomasjacquin/allsky-website#3]
not so much an issue or problem, but as i'm not good with the workings of web pages, is there an option to change the display order of the images/videos so that newest is on top, instead of having to scroll all the way to the bottom (generating thumbnails the entire way) for the newer data? 

Thanks again for all the support and this awesome project! finally got my v0.6 up and running after my 0.5 crashed.

**Comment by thomasjacquin** [comment]
Hey Jim,

Change line 20 of /var/www/html/includes/images.php from `asort` to `arsort`. That should do it

**Comment by jcauthen78** [comment]
thank you sir! it worked perfectly
