### ISSUE TITLE
Using Startrails thumbnails for videos

### ISSUE THREAD

**Issue by CleverJay** [thomasjacquin/allsky-website#32]
What do I need to change in videos/index.php to use the startrail image as the thumbnail for the videos?

**Comment by thomasjacquin** [comment]
Replace `src="../aurora_snap.jpg"` on this line https://github.com/thomasjacquin/allsky-website/blob/master/videos/index.php#L39 by this `src="./thumbnails/startrails-".$date.".jpg"`

Not tested but that's the idea.

**Comment by CleverJay** [comment]
Thanks Thomas

**Comment by CleverJay** [comment]
Had to make the following changes but now it works: `if (file_exists("../startrails/thumbnails/startrails-".$date.".jpg")){
				//echo "<img style='display:none' src='thumbnails/".$date.".gif'>";
				echo "<a href='./$file'><div class='day-container'><div class='image-container'><img id=".$date." src='../startrails/thumbnails/startrails-".$date.".jpg' title='$year-$month-$day' onmouseenter='onImgEnter(this)' onmouseleave='onImgLeave(this)'/></div><div>$year-$month-$day</div></div></a>";
			} else {
				echo "<a href='./$file'><div class='day-container'><div class='image-container'><img id=".$date." src='../startrails-snap.jpg' title='$year-$month-$day'/></div><div>$year-$month-$day</div></div></a>";
			}`
