### ISSUE TITLE
Timelapses, keograms and startrails in reverse order

### ISSUE THREAD

**Issue by HamOP** [thomasjacquin/allsky-website#34]
I just saw that on my install of the website, all of the nightly files are ordered "oldest one first", while in the demo website and all the other ones I looked at, order is reversed and the last night is shown first.
It was easy to fix by replacing the `asort()` by `arsort()`, but I don't understand why this happens on my site. Could that have something to to do with PHP versions?

**Comment by AstroHighlander** [comment]
Hi HamOP - where do I find the asort( ) or arsort( ) commands(s)?  I want to fix this as well. Eric

**Comment by HamOP** [comment]
In the `index.php` files in the videos, keograms and star trails folders. Look for the line `asort($files);`.

**Comment by AstroHighlander** [comment]
HamOP thanks very much for that - it worked a treat!  Sooooo easy when you know how

**Comment by EricClaeys** [comment]
HamOP,
If this issue is resolved, would you please close it?
Thanks - Eric

**Comment by Kilis71** [comment]
> Nei `index.php`file nelle cartelle video, keogrammi e scie stellari. Cerca la riga `asort($files);`.

in the latest version this line of code is missing

**Comment by EricClaeys** [comment]
@Kilis71, 
Most of the code in the the `index.php` files in the keograms, startrails, and videos directories moved to a common location in the current release, to make maintenance easier.  The `asort($files)` command is now in the `functions.php` file.

Are you having a problem with sorting?

**Comment by Kilis71** [comment]
ok, thank you very much
