### ISSUE TITLE
Issue with transfering images from Pi to ftp 

### ISSUE THREAD

**Issue by Gary79** [thomasjacquin/allsky-website#36]
Hi Thomas, can you help I am struggling to get the Pi to send anything to the ftp host.
Website is all set up and I am recieving all to the Pi interface but just keep getting a loading image on the website. 

Here's the URL allsky.salfordastro.org.uk 

Cheers 
Gary

**Comment by horatti** [comment]
Hi Gary!

Here is an example if you use Thomas' original files:

lftp "ftp"://"username":"$PASSWORD"@"allsky.salfordastro.org.uk":"/subfolder (if any..)" -e "set net:max-retries 1; set net:timeout 20; put $FILENAME-resize.$EXTENSION; bye"
..... or so if a certificate problem occurs:
lftp "ftp"://"username":"$PASSWORD"@"allsky.salfordastro.org.uk":"/subfolder (if any..)" -e "set ftp:ssl-allow off; set net:max-retries 1; set ssl:verify-certificate false; set net:timeout 20; put $FILENAME-resize.$EXTENSION; bye"

Try it on the command line first (without "bye"), then paste it into the appropriate files.

Ati

**Comment by Gary79** [comment]
Thanks Ati All sorted now

**Comment by rseg80** [comment]
> Hi Gary!
> 
> Here is an example if you use Thomas' original files:
> 
> lftp "ftp"://"username":"$PASSWORD"@"allsky.salfordastro.org.uk":"/subfolder (if any..)" -e "set net:max-retries 1; set net:timeout 20; put $FILENAME-resize.$EXTENSION; bye"
> ..... or so if a certificate problem occurs:
> lftp "ftp"://"username":"$PASSWORD"@"allsky.salfordastro.org.uk":"/subfolder (if any..)" -e "set ftp:ssl-allow off; set net:max-retries 1; set ssl:verify-certificate false; set net:timeout 20; put $FILENAME-resize.$EXTENSION; bye"
> 
> Try it on the command line first (without "bye"), then paste it into the appropriate files.
> 
> Ati

Where does this code go?  I’m having the same issue.  Thanks

**Comment by horatti** [comment]
Hi!

In any file that uploads somewhere on ftp. For example:
endOfNight.sh
saveImageDay.sh
saveImageNight.sh
uploadForDay.sh

The files are in the "scripts" subdirectory.

**Comment by EricClaeys** [comment]
Gary,
If this issue is resolved, and it sounds like it is, would you please close it?
Thanks - Eric
