### ISSUE TITLE
Messier Objects on overlay not showing

### ISSUE THREAD

**Issue by wramey7274** [thomasjacquin/allsky-website#41]
Greetings:

The Messier Objects are not showing up on the overlay.  I have included below my virtualsky.json file. If anyone could help me identify the issue, I would certainly appreciate it. The link for my allsky cam is: [https://www.inthebeginning.org/allsky/](url)

**virtualsky.json** 

{
	"id":"starmap",
	"projection":"fisheye",
	"width": 900,
	"height": 972,
	"constellations": true,
	"mouse": false,
	"gridlines_eq": true,
	"keyboard": false,
	"showdate": false,
	"showposition": false,
	"constellationlabels": true,
	"sky_gradient": false,
	"gradient": false,
	"transparent": true,
	"objects": "M1;M4;M7;M8;M11;M13;M16;M27;M31;M42;M45;M51;M57;M81;M82;M101",
	"lang": "en"
}

Thank you.

**Comment by thomasjacquin** [comment]
Hi William, try replacing `http` by `https` in this file https://github.com/thomasjacquin/allsky-website/blob/master/virtualsky/virtualsky.js#L1161

I believe the browser is giving an error when loading the Messier objects because they are pulled from an http source and your website is using the https protocol. I haven't tried it but I think it'll work.

**Comment by wramey7274** [comment]
Thomas,

 

You are a genius! Of course that was the issue. When I was looking at the code for virtualsky/virtualsky.js last week, I never considered that was the issue, even though when I code I make sure that the https is part of the URL, for the server will not render an external source without it.

 

Again, you are a genius! Thank you very much for your very rapid reply.

 

I should receive my additional hardware tomorrow or Thursday, and then I can pitch my allsky cam properly to achieve the overlay much more exact to the live-view than I have it at this time.

 

Thank you for your time invested, your skill, and your broad knowledge of troubleshooting. You certainly deserve another “cup of coffee” on me.

 

Bill

 

Bill Ramey

Email:  ***@***.***> ***@***.***

Cell: 404-285-9850

**Comment by leitmori** [comment]
Unfortunately the LookUP service has been suspended: https://www.strudel.org.uk/lookUP/

**Comment by leitmori** [comment]
Fixed with PR #42
