### ISSUE TITLE
Need to flip virtual sky overlay around North is South and South is North Currently

### ISSUE THREAD

**Issue by PhotonPup** [thomasjacquin/allsky-website#46]
Default view for virtual sky is showing North is South and South is North in my current view. Is there a way to flip this around?

**Comment by EricClaeys** [comment]
Try modifying the "az" variable in the config.json file.  az=0 puts North at the bottom of the picture.
I believe this is mentioned in the README document.

**Comment by PhotonPup** [comment]
Hello EricClaeys,
Thank you for the information. One issue I am running into with the config.js is nothing in there is shown on the AllSky view so I changed in-line the index.html file which worked. 
Ill give this a shot again however and wait a day or so to see if this takes.

**Comment by PhotonPup** [comment]
I left the editing in the index.html file and swapped just az = 0 in config.js. All good. thank you.

**Comment by EricClaeys** [comment]
PhotonPup,
If this issue is resolved, please close it.
Thanks - Eric

**Comment by PhotonPup** [comment]
Closing issue.
