### ISSUE TITLE
video thumbnails are created with each call

### ISSUE THREAD

**Issue by hoetzgit** [thomasjacquin/allsky-website#48]
functions.php

The thumbnails file are checked with file_exists (line 87) before they are "renamed" with $thumbnail = str_replace(".mp4", ".jpg", $thumbnail); in line 91. 

The check should be done after renaming.

**Comment by EricClaeys** [comment]
Thanks for pointing that out.  I just put in a fix for Thomas' review.
It's nice now that the page will create the video thumbnails automatically, rather than using the aurora picture or the "No Thumbnail" picture.

Eric
