### ISSUE TITLE
New site up and running in Cape Town, South Africa

### ISSUE THREAD

**Issue by lanties** [thomasjacquin/allsky-website#51]
Thomas, 

Thank you for your amazing work on this!  Here is a link to my site [https://www.aot.co.za/allsky/](url)  

For some reason the videos never created thumbnails so I modified the index.php in ./vidoes to use ffmpegthumbnailer

sudo apt-get install ffmpegthumbnailer 

I have attached the changed version in case it may help someone.

Again thank you

Kind regards
Johan
[index.zip](https://github.com/thomasjacquin/allsky-website/files/7142403/index.zip)

**Comment by thomasjacquin** [comment]
Hi Johan,
Thanks for sharing your thumbnail creation code and your sky. First one in Africa! I added you to the map.

Cheers,
Thomas
