### ISSUE TITLE
Sorting

### ISSUE THREAD

**Issue by maserowik** [thomasjacquin/allsky-website#54]
I there a way to change the sorting on the webpage.  now it sorts the oldest to the newest.  i like to sort it from newest to oldest.  I know in the prior version it was a done with the index file.

**Comment by EricClaeys** [comment]
@maserowik you can use arsort() instead of asort() in /var/www/html/allsky/functions.php.

If after making this change it resolves your question, please close the issue.  Thanks.

**Comment by maserowik** [comment]
Thanks that worked.  I had to modify on my web hosting site.

**Comment by calberts** [comment]
@maserowik 

I checked it for me this doesn't work

	//asort($files);
	arsort($files);

![image](https://user-images.githubusercontent.com/6442948/139587893-11add2db-f680-42d8-a8a3-bea95fb801e8.png)

**Comment by EricClaeys** [comment]
@calberts, in which file did you change the sort from asort() to arsort()?
In /var/www/html/includes there is
* arsort() in days.php
* rsort() in fuctions.php
* asort() in images.php

Did changing asort() to arsort() do ANYTHING?

When I changed asort() to arsort() in images.php, it worked for me.

**Comment by maserowik** [comment]
@EricClaeys 
I only changed the command in function.php
I check on my hosting site and the timelapse/keograms and startrails all have the newest listed first.
Mike
