### ISSUE TITLE
 aurora image

### ISSUE THREAD

**Issue by maserowik** [thomasjacquin/allsky-website#68]
Is there a way to bring back the Aurora Iage?

https://github.com/thomasjacquin/allsky-website/issues/26

Mike

**Comment by maserowik** [comment]
@EricClaeys 
Understand that there is a fix for this.  Thanks for you assistance on this Eric.

Mike

**Comment by EricClaeys** [comment]
@maserowik I am working on a permanent solution.  In the meantime, you just have to update the data.json file in the same directory as the config.js file.  Assuming the data.json file in ~/allsky/tmp is updated as part of the endOfNight.sh script you can simply copy the file.
You also need to make sure you have the display auroras option turned on in config.js and that you are NOT taking daytime images.

**Comment by maserowik** [comment]
@EricClaeys 
So i update my config.js and added the following
![image](https://user-images.githubusercontent.com/25713782/148959416-1fa71f50-527a-4f23-a7a4-5973a321a377.png)

the data.json is appears to be correct for me.
![image](https://user-images.githubusercontent.com/25713782/148959623-c155b31e-3450-49d8-9f4d-7efe0e4947fc.png)

daytime capture and daytime save are set to false.
![image](https://user-images.githubusercontent.com/25713782/148959813-363bafc0-0108-4ed3-b5be-50d29f1cec8c.png)

but on the website the still seeing the image
![image](https://user-images.githubusercontent.com/25713782/148959926-b141213c-6f23-4cea-85bb-60ed9dc4b519.png)


any idea of what step I am missing?

Mike

**Comment by EricClaeys** [comment]
@maserowik Mike, during the day when the image is showing, press F12 and on the right side click on the "Console" link.  You may need to first click on >>> to display the Console link.
Let me know what it says.  It might be something like "It's  nighttime".

**Comment by maserowik** [comment]
@EricClaeys 
here is the website f12 setting
![image](https://user-images.githubusercontent.com/25713782/148971682-6c16262a-b37a-4fdf-885c-cbfc88291ec6.png)

here is from the admin console
![image](https://user-images.githubusercontent.com/25713782/148971781-e5ae3a2e-8f2a-40fe-a18e-63f293480b42.png)

Mike

**Comment by maserowik** [comment]
I went back to showing the live camera image.

**Comment by EricClaeys** [comment]
@maserowik There is a new "controller.js" file that will hopfully show the aurora image during the day when you aren’t taking pictures.   The algorithm to determine daytime didn't always work.
Let me know how it goes.

**Comment by EricClaeys** [comment]
Closing - issue fixed.  The old website code thought it was nighttime even when it was daytime so it never displayed the aurora image.
The new version also has a much more obvious "Come back at xxx" message - it's larger, brighter, and includes the time.
