### ISSUE TITLE
Installing read-only website for allsky

### ISSUE THREAD

**Issue by HPWever** [thomasjacquin/allsky-website#7]
When you already run a Thomas Jacquin Allsky Camera and you use the admin website to manage, you may also want to install a read-only site to be able to give away to friends.
In the attached document I decribe how (and some tips).
[installing allsky-website.docx](https://github.com/thomasjacquin/allsky-website/files/3244654/installing.allsky-website.docx)

**Comment by EricClaeys** [comment]
Closing - newer versions include the "public.php" web page.
