### ISSUE TITLE
Webpage shows different on multiple machines

### ISSUE THREAD

**Issue by maserowik** [thomasjacquin/allsky-website#75]
@EricClaeys 
so I thought all was working but not something is not working 
So I have two browser open and point to n3bsq.com/allsky
one shows this
![image](https://user-images.githubusercontent.com/25713782/150002194-45aab731-1571-4e0b-bf40-5059688e373c.png)

and the other show this.
![image](https://user-images.githubusercontent.com/25713782/150002239-07b1c354-0e3d-4865-a6a0-635e5db2a97c.png)

any suggestion?

Mike

**Comment by EricClaeys** [comment]
@maserowik Try refreshing the top browser when in F12 mode.  Refreshing outside of F12 mode doesn't always re-read all the files the page requests, like the configuration pages.
What's in your "config.js" file for **imageName** ?  If you changed it, what did it used to be?

If I had to guess, I'd say "config.js" used to have "imageName: /current/tmp/image.jpg" and now has "imageName: image.jpg" and the top browser is still using the old value and the bottom browser is using the correct, new value.

**Comment by maserowik** [comment]
@EricClaeys 
here is my config.js
![image](https://user-images.githubusercontent.com/25713782/150534519-c30833c0-d957-4e8a-8bb2-f4e93e97d179.png)




![image](https://user-images.githubusercontent.com/25713782/150534251-bc8899b8-6f14-4a5d-a793-adea8b6ee3be.png)

i went back to showing images all the time due to i can not get the aurora to show 100 percent of the time but now I got the following message at the top of my web site?

**Comment by maserowik** [comment]
@EricClaeys 
I changed the false to a true in the data.json to get rid of the red nag saying come back when it is dark.  

Not sure on this.

Mike

**Comment by EricClaeys** [comment]
@maserowik Obviously I have more work to do.  I have an updated version on my Pi that I'm working on.

**Comment by EricClaeys** [comment]
@maserowik Did the F12 refresh work?  Are the two websites now displaying the same thing? If so, let's close this Issue.  The aurora forecast not displaying correctly we'll track via Issue # 74.

**Comment by maserowik** [comment]
@EricClaeys 
The F12 did work.  i will close this and keep 74 open
