### ISSUE TITLE
403 Forbidden

### ISSUE THREAD

**Issue by WirthmU** [thomasjacquin/allsky-website#8]
I have uploaded your website code and the main page is working. However - as soon as I want to access any of the file folders (videos, keograms, startrails) I get the following error:

`You don't have permission to access /~Berna_felix/Saanenmoeser/allsky/startrails/ on this server.`

Any help to this?

**Comment by thomasjacquin** [comment]
What permissions do you have on this directory? Try setting it to 755 using your FTP client

**Comment by WirthmU** [comment]
I think it has been a problem with my commercial provider not allowing to run PHP. 

The website in the meanwhile has been transferred to my private Synology NAS and this resolved that problem.
